// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtzuvulnziwoodvuyrmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0enV2dWxueml3b29kdnV5cm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTI4NzQsImV4cCI6MjA1OTAyODg3NH0.-zFAVzYcue5a4gK94CTYCykcCUu-qrPj7p9OGSYSEV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);